export { default as App } from './App';
export { default as CreateRoutine } from './CreateRoutine';
export { default as CreateActivity } from './CreateActivity';
export { default as Header } from './Header';
export { default as Login } from './Login';
export { default as Routines } from './Routines';
export { default as MyRoutines } from './MyRoutines';
export { default as Register } from './Register';
// export { default as SendMessage } from './SendMessage';
export { default as UpdateRoutine } from './UpdateRoutine';
export { default as UpdateActivity } from './UpdateActivity';
export { default as ViewSingleRoutine } from './ViewSingleRoutine';
export { default as ViewSingleActivity } from './ViewSingleActivity';
export { default as Activities } from './Activities';